### ISSUE TITLE
Video's label line count doesn't equal to the video's frame count

### ISSUE THREAD

**Issue by leon1117** [eborboihuc/Deep360Pilot-CVPR17#3]
I use your model to predict a video selected from data/frature* directory , I fount that the predict result line count doesn't equal to the real video' frame count, and I check this video's label information from data 'Deep360Pilot_label' you provided, it doesn't equals to the real video' frame count too, the real video is download from youtube with id, could you please explain it?
thanks.

**Comment by eborboihuc** [comment]
If I understand correctly, your questions are as follows:

1) Predict result length does not equal to the real video frame numbers

2) Label length does not equal to the real video frame numbers

3) The real video you mean is download from YouTube

The reason behind this is because we are using `Clip-based data` instead of a whole video.
If you take a look at the 360-Sports dataset section of our paper, you will find out that we use video clips instead of the whole videos in our whole settings. 
Let's use an example to demonstrate this. The difference between them is that `OWAgi_ucedY` stands for a video name while `OWAgi_ucedY_*` stands for multiple clips sampled from different parts of that video. 
We are planning to release these data in the future. But we still need to figure out to what degree of data can we provide since we don't have the copyrights of those videos.

I'll close this issue for now. If you have more question, you are welcome to re-open it.

**Comment by liuxy1005** [comment]
Do you have this dataset? Can you share it with me? Thank you very much
